## The makeCacheMatrix function generates a special matrix which is able to be 
## recalled by cacheSolve and if the matrix's inverse has not been solved
## cacheSolve will solve it.

## makeCacheMatrix function generates an object which is connected to a matrix.
## additionally a list of functions are attached to this matrix which allow
## the setting of the matrix, returning of the matrix, setting the
## matrix inverse, and returning the matrix inverse.

makeCacheMatrix <- function(x = matrix()) {
	 #generate a null variable to later store the inverse in
	i <- NULL
	
	#create a function which can set/reset the matrix
	set <- function(z){
				x <<- z
				i <<- NULL
		}
	# create a function which returns the cached matrix
	get <- function() x
	
	# create a function which will set the inverse to i
	setinverse <- function(solve) i <<-solve
	
	# create a function which will return the value stored in i(later will have
	#the inverse
	getinverse <- function() i
	
	# create a list of the functions embedded within the main function
	list(set = set, get = get, setinverse = setinverse, 
	getinverse = getinverse)
}


## cacheSolve checks to see if a cached matrix generated by makeCacheMatrix
## has an inverse solution. If the cached matrix does then the message getting
## cached data will be printed along with the inverse. If the inverse has
## not been solved the function will solve it set it to the cached matrix
## and return it.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
	##Access the special matrix and get what is stored in the inverse 
	##variable
	i <- x$getinverse()
		
	#check to see if the inverse variable is empty by checking if it is NULL
	if(!is.null(i)){
		message("getting cached data")
		return(i)
	}
	matrix_temp <- x$get()  # if inverse is null access matrix
	i <- solve(matrix_temp) # generate inverse of the matrix
	x$setinverse(i)        	# set the inverse in the cached matrix
	i			            # return the inverse
}